development:
  sessions:
    default:
      database: mongoid
      hosts:
        - localhost:27017
  options:
    raise_not_found_error: false

test:
  sessions:
    default:
      database: wally_test
      hosts:
        - localhost:27017
  options:
    raise_not_found_error: false
